INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("37bdabad-1849-4986-a8cd-0867a404ac44","1","BG- Baggage","SP-Sporting Equipment","Sport Equip Large Dimensions","XS - Between 51lb/24 and 70lb/32kgs","","Sporting Equipment - Large Dimensions","AUD","110");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("9516cdff-6562-4ea6-b7d5-40e9fa141d07","2","BG- Baggage","SP-Sporting Equipment","Bowling Equipment upto 45 kgs","BE-Bowling Equipment","45- Upto 100lb/45kg","Bowling Equipment","","","","AUD","40");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("16054367-92e6-43d3-9e42-90fa9fc89aed","3","BG- Baggage","SP-Sporting Equipment","Golf Equipment Upto 45kgs","GF- Golf Equipment","45- Upto 100lb/45kg","Golf Equipment upto 45kgs","","","","AUD","85");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("692a92bd-e1fb-438d-baf4-29f90bc5e1a1","4","IE - In-flight Entertainment","HS - Headset","Headset BOSE QC15","","","Noise Cancellation headset BOSE QC15 to help you relax and enjoy","","","","AUD","50");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("4e9ff7a2-7c0e-4a15-af85-39c43d84dd49","5","IE - In-flight Entertainment","IT - Internet Access","OnAir Wi-Fi","","","Inflight Wi-Fi connectivity","","","","AUD","40");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("1d99cf4d-54ed-4741-9be0-8abd0b27d848","6","IW- In-flight Wellness","","Shower Spa","","","State-of-the-art shower system to the classic walnut and marble design to fine linens","","","","AUD","200");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("735c501e-7e16-43f6-b459-6bd70e677723","7","IG- Inflight Gourmet","Chocolates","Belgian Organic Chocolates","","","Hand crafted organic Belgian chocolates","","","","AUD","48");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("fc8e8219-2655-4a71-aec4-85b311d586c1","8","IW- In-flight Wellness","","Lumbar Pillow","Therm-A-Rest Lumbar Pillow","","Ergonomically designed lumbar supprt for your mid and lower back.","","","","AUD","30");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,IMAGE_THUMBNAIL_URL,IMAGE_LARGE_URL,IMAGE_TOOL_TIP,CURRENCY,PRICE)
values ("b141032e-69d7-437a-a35d-bab2acf70b45","9","IW- In-flight Wellness","","Tempur-Pedic Sleep Mask","","","Sleep mask for total darkness and a comfortable fit","","","","AUD","40");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("908d3b54-e838-4a9b-af88-d0245d21357b","10","MD - Medical","IR - Incubator","Incubator","NB - Newborn Medical","","Incubator for newborns","AUD","100");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("892e88dc-03b7-4b45-88fc-90aa181ccd43","11","UN - Unaccompanied","AS - Assistance","Meet and Greet Services - Max Group of 5","MG - Meet and Greet","GR - Group - Max 5","Assistance with checkin and boarding for a group of 5","AUD","100");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("085591ee-5f8f-45bd-af8f-50f0504e33f8","12","UN - Unaccompanied","AS - Assistance","Meet and Greet Services - Family","MG - Meet and Greet","FY - Family","Assistance with checkin and boarding for a family","AUD","200");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("4b7c5277-dd6c-4dff-a247-cee94945e593","13","ML - Meal/Beverage","SN - Snack","Kosher Snack","KO - Kosher","","Kosher Snack","AUD","25");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("c5ab9e02-f94f-49a5-bbca-06477b2ba264","14","PT - PETS","PH - In Hold","Medium Pet in hold 9kg 25kg","MD - Medium","08 - Up to 18 lb/8 kg","Medium Pet placed in the  aircraft belly  - 9kg 25 kg","AUD","200");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("33e83b03-3600-4431-977d-eddded1ade20","15","UN - Unaccompanied","AS - Assistance","Meet and Greet Services - 1 Person","MG - Meet and Greet","OP - One Person","Assistance with checkin and boarding for 1 person","AUD","45");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("3b1991b0-752c-42f3-941a-9a05d6c61b2d","16","BG- Baggage ","Ergonomic luggage handle","Ergonomic luggage handle","","Ergonomic luggage handle","Ergonomically designed luggage handle which reduces stress on the wrists","AUD","28");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("a3116e59-62cb-4254-89b4-63cbe88e7d7d","17","MD - Medical","OX - Oxygen","Oxygen","","","Oxygen","AUD","175");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("45f28690-490f-4c97-bcb2-d1bce6fac8fe","18","MD - Medical","SC - Stretcher","Stretcher","","","Stretcher","AUD","100");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("da17ee6d-ef9e-4388-b635-3fb8ff87d638","19","Assistance","Inflight Assistance","Chat with Cabin crew","Chat with Cabin crew","","Chat with Cabin crew","","");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("1862e5cd-d0a3-45ef-b82b-bc2948bf1158","20","BG- Baggage","","Pre-Paid Baggage","","","Pre-purchase your baggage allowance to save time and money at check-in.","AUD","65");

INSERT INTO ANCILLARY_MASTER (UUID,ANC_MASTER_CODE,GROUP_CODE,SUB_GROUP,COMMERCIAL_NAME,DESCRIPTION1,DESCRIPTION2,WEB_DESCRIPTION,CURRENCY,PRICE)
values ("3d7be3a8-e23a-4c81-9bcf-c60e7a3f8754","21","MD - Medical","WH - Wheelchair","Wheelchair","","","Wheelchair in Airport","AUD","50");


UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='sports-baggage.png'
WHERE ANC_MASTER_CODE=1;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='bowling.png'
WHERE ANC_MASTER_CODE=2;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='golf-equipment.png'
WHERE ANC_MASTER_CODE=22;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='headset.png'
WHERE ANC_MASTER_CODE=4;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='onair-wi-fi.png'
WHERE ANC_MASTER_CODE=5;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='shower.png'
WHERE ANC_MASTER_CODE=6;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='chocolate.png'
WHERE ANC_MASTER_CODE=7;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='flatBed.png'
WHERE ANC_MASTER_CODE=8;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='sleep-mask.png'
WHERE ANC_MASTER_CODE=9;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='incubator.png'
WHERE ANC_MASTER_CODE=10;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='meet-and-greet-group.png'
WHERE ANC_MASTER_CODE=11;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='meet-and-greet-family.png'
WHERE ANC_MASTER_CODE=12;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='special-meal.png'
WHERE ANC_MASTER_CODE=13;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='pet.png'
WHERE ANC_MASTER_CODE=14;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='meet-and-greet-one.png'
WHERE ANC_MASTER_CODE=15;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='ergonomic-luggage.png'
WHERE ANC_MASTER_CODE=16;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='oxygen.png'
WHERE ANC_MASTER_CODE=17;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='stretcher.png'
WHERE ANC_MASTER_CODE=18;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='chat-with-cabin-crew.png'
WHERE ANC_MASTER_CODE=19;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='baggage.png'
WHERE ANC_MASTER_CODE=20;
UPDATE ANCILLARY_MASTER SET IMAGE_THUMBNAIL_URL='wheelchair.png'
WHERE ANC_MASTER_CODE=21;

UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='sports-baggage_large.png'
WHERE ANC_MASTER_CODE=1;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='bowling_large.png'
WHERE ANC_MASTER_CODE=2;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='golf-equipment_large.png'
WHERE ANC_MASTER_CODE=22;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='headset_large.png'
WHERE ANC_MASTER_CODE=4;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='onair-wi-fi_large.png'
WHERE ANC_MASTER_CODE=5;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='shower_large.png'
WHERE ANC_MASTER_CODE=6;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='chocolate_large.png'
WHERE ANC_MASTER_CODE=7;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='flatBed_large.png'
WHERE ANC_MASTER_CODE=8;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='sleep-mask_large.png'
WHERE ANC_MASTER_CODE=9;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='incubator_large.png'
WHERE ANC_MASTER_CODE=10;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='meet-and-greet-group_large.png'
WHERE ANC_MASTER_CODE=11;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='meet-and-greet-family_large.png'
WHERE ANC_MASTER_CODE=12;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='special-meal_large.png'
WHERE ANC_MASTER_CODE=13;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='pet_large.png'
WHERE ANC_MASTER_CODE=14;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='meet-and-greet-one_large.png'
WHERE ANC_MASTER_CODE=15;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='ergonomic-luggage_large.png'
WHERE ANC_MASTER_CODE=16;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='oxygen_large.png'
WHERE ANC_MASTER_CODE=17;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='stretcher_large.png'
WHERE ANC_MASTER_CODE=18;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='chat-with-cabin-crew_large.png'
WHERE ANC_MASTER_CODE=19;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='baggage_large.png'
WHERE ANC_MASTER_CODE=20;
UPDATE ANCILLARY_MASTER SET IMAGE_LARGE_URL='wheelchair_large.png'
WHERE ANC_MASTER_CODE=21;
