---
# tasks file for ea

- name: check if ea_aics release is there
  stat: path=/vagrant/_rel/ea_aics/bin/ea_aics
  register: check_ea_aics_exe

- name: check if ea_cs release is there
  stat: path=/vagrant/_rel/ea_cs/bin/ea_cs
  register: check_ea_cs_exe

- name: check if ea_aics release is runnning
  command: _rel/ea_aics/bin/ea_aics ping chdir=/vagrant/
  failed_when: false
  register: check_ea_aics_running
  when: check_ea_aics_exe.stat.exists

- name: check if ea_cs release is runnning
  command: _rel/ea_cs/bin/ea_cs ping chdir=/vagrant/
  failed_when: false
  register: check_ea_cs_running
  when: check_ea_cs_exe.stat.exists

- name: ensure ea_aics release is not running
  command: _rel/ea_aics/bin/ea_aics stop chdir=/vagrant/
  when: check_ea_aics_exe.stat.exists and check_ea_aics_running.stdout.find('pong') != -1

- name: ensure ea_cs release is not running
  command: _rel/ea_cs/bin/ea_cs stop chdir=/vagrant/
  when: check_ea_cs_exe.stat.exists and check_ea_cs_running.stdout.find('pong') != -1

- name: clean releases
  command: make distclean chdir=/vagrant/

- name: generate releases
  command: make rel chdir=/vagrant/

- name: wait fot rabbitmq
  wait_for: port=5672 delay=10

- name: start the ea_aics release
  command: _rel/ea_aics/bin/ea_aics start chdir=/vagrant/

- name: start the ea_cs release
  command: _rel/ea_cs/bin/ea_cs start chdir=/vagrant/
